[package]
name = "wasm_2048"
version = "0.1.0"
author = "midori shibukawa"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"

getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"